arMenu1 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",
"RCO0002 Informe de Demonstrativo","http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0002",0,                                                                                                                            
"RCO0003 Consulta Demonstrativo", "http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0003",0,                                                                                                                                 
"RCO0004 Consulta Multas" ,"http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0004",0,                                                                                                                                        
"RCO0005 Consulta Extrato Movimentação","http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0005",0,                                                                                                                           
"RCO0006 Consulta Cumprimento Compulsório" ,"http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0006",0,                                                                                                                       
"RCO0007 Consulta Custos" ,"http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0007",0,                                                                                                                                        
"RCO0008 Consulta Compulsórios" ,"http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0008",0,                                                                                                                                  
"RCO0009 Consulta Alterações Outras Reservas /Caixa Demonstrativo","http://Srv-gersut:8089/spb/ValidateMsg.asp?selectl=RCO0009 ",0
)
  
arMenu2 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",                                                                                           
"STR0003 Liquidação de Transferência de Numerário","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0003 ",0, 
"STR0004 Transferência de Reserva" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0004 ",0,                                                                                              
"STR0007 Transferência de Conta IF para Conta Cliente" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0007 ",0,                                                                                            
"STR0008 Transferência entre Contas de diferentes Titularidade", "http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0008 ",0,                                                                                   
"STR0009 Transferência entre Contas de mesma Titularidade","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0009 ",0,                                                                                         
"STR0010 Transferência para Devolução de Transferência Indevida ", "http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0010 ",0,                                                                                 
"STR0011 Cancelamento de Lançamento Pendente" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0011 ",0,                                                                                                     
"STR0012 Consulta Lançamentos", "http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0012 ",0,                                                                                                                                  
"STR0013 Consulta Saldo Reserva Bancária", "http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0013 ",0,                                                                                                                       
"STR0014 Consulta Extrato" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STR0014 ",0)
 
arMenu3 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",                                                                                                                                    
"RDC0001 Consulta Títulos Redescontáveis " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0001 ",0,                                                                                                                      
"RDC0002 Redesconto Intradia " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0002 ",0,                                                                                                                    
"RDC0003 Redesconto Overnight " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0003 ",0,                                                                                                                   
"RDC0004 Redesconto Vinculado a Aquisição " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0004 ",0,                                                                                                       
"RDC0005 Conversão Redesconto Intradia em Overnight ou " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0005 ",0,                                                                                          
"RDC0006 Consulta Redescontos ","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0006 ",0,                                                                                                                                  
"RDC0007 Pagamento de Redesconto","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0007 ",0,                                                                                                                  
"RDC0008 Pagamento de Redesconto Vinculado a Venda ","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=RDC0008 ",0)
 arMenu4 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",                                                                                             
"CIR0001 Estatística Semanal de Movimentação ","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0001 ",0,                                                                                                       
"CIR0002 Consulta Estatística Movimentação" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0002 ",0,                                                                                                                     
"CIR0003 Saque de Numerário " ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0003 ",0,                                                                                                                     
"CIR0004 Cancelamento de Saque de Numerário" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0004 ",0,                                                                                                      
"CIR0005 Depósito de Numerário","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0005 ",0,                                                                                                                    
"CIR0006 Cancelamento de Depósito de Numerário" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0006 ",0,                                                                                                   
"CIR0008 Consulta Movimentações de Numerário","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0008 ",0,                                                                                                                    
"CIR0009 Consulta Lançamentos Pendentes na Conta Transitória MECIR","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0009 ",0,                                                                                              
"CIR0012 Transferência para Ajuste de Numerário Depositado a menor","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0012 ",0,                                                                                
"CIR0013 Consulta Relação Custodiante por Estado","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CIR0013 ",0)
 arMenu5 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",                                                                                                             
"SLB0002 Pagamento de Lançamento BACEN" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=SLB0002 ",0,                                                                                                           
"SLB0004 Cancelamento de Lançamento SLB Pendente" ,"http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=SLB0004 ",0,                                                                                                 
"SLB0006 Consulta Lançamentos SLB","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=SLB0006 ",0,                                                                                                                              
"SLB0007 Requisição de Pagamento ao BACEN","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=SLB0007 ",0)
 arMenu6 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",                                                                                                                          
"STN0001 Transferência de Reserva para Tesouro","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STN0001 ",0,                                                                                                   
"STN0002 Transferência Repasse Arrecadação","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STN0002 ",0,                                                                                                        
"STN0003 Recolhimento a Maior a ser compensado","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=STN0003 ",0)
 arMenu7 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",
"LDL0003 Informa Resultado Liquido de Negociações Divergente","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0003 ",0,                                                                                                 
"LDL0004 Transferência do Resultado Liquido Negociação","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0003 ",0,                                                                                            
"LDL0008 Transferência para Liquidação de Eventos e Emissões","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0004 ",0,                                                                                      
"LDL0011 Transferência da Conta Corrente Câmara para Conta","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0011 ",0,                                                                                        
"LDL0014 Transferência Depósito de Garantias Financeiras","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0014 ",0,                                                                                          
"LDL0020 Transferência do Resultado Líquido","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0020 ",0,                                                                                                       
"LDL0022 Requisição de Transferência para Depósito Operacional","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=LDL0022 ",0) 
 arMenu8 = new Array(
200,
"","90",
"#0066CC","",
"#E9E9E9","#C0C0C0",
"#0066CC","#0066CC",
"CMP0002 Requisição de Transferência para Depósito Operacional COMPE","http://srv-gersut:8089/spb/ValidateMsg.asp?selectl=CMP0002 ",0)                                                  